spring:
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  datasource:
    url: jdbc:mariadb://localhost:3306/nome_app_db
    username: fake
    password: fake
    driver-class-name: org.mariadb.jdbc.Driver

logging:
  level:
    org.springframework.web: ERROR